export const scenarios = [
  { id: 'napoli', city: 'Napoli', type: 'Local fan', caption: 'La partita comincia sotto casa.', title: 'QUI, OGNI\nGIORNO.', intro: 'La città, il rito, la strada verso lo stadio. Un Napoli che fa parte della giornata.', language: 'Italiano', focus: 'Vivere il matchday', editorial: 'I luoghi del tuo rito', action: 'Prepara il tuo matchday', cultural: 'Luoghi', recap: 'La vicinanza diventa un rito.', match: ['Il percorso verso lo stadio, le informazioni di accesso e il tuo rituale.', 'L’essenziale a colpo d’occhio, per lasciare spazio alla partita.', 'Un ricordo da scegliere e la storia della serata da ritrovare.'] },
  { id: 'milano', city: 'Milano', type: 'Away fan', caption: 'Lontano, mai fuori.', title: 'DISTANTI.\nDENTRO.', intro: 'Il legame non misura i chilometri. Contenuti e rituali che fanno sentire parte della stessa serata.', language: 'Italiano', focus: 'Sentirsi parte', editorial: 'La città che porti con te', action: 'Entra nel rito partita', cultural: 'Storie', recap: 'La distanza diventa appartenenza.', match: ['Prepara il tuo rito a distanza e scegli cosa seguire.', 'Un punto di accesso al racconto della partita, senza distrazioni.', 'Ritrova i passaggi chiave e scegli il ricordo da portare con te.'] },
  { id: 'londra', city: 'Londra', type: 'Roots fan', caption: 'Le radici viaggiano con te.', title: 'YOUR ROOTS.\nYOUR CLUB.', intro: 'Storie, parole e calcio: una relazione che attraversa generazioni e lingue.', language: 'English', focus: 'Ritrovare le radici', editorial: 'Words that feel like home', action: 'Explore match mode', cultural: 'Parole', recap: 'Le radici diventano una storia da condividere.', match: ['A matchday guide in your language, with local-time information in a connected product.', 'Follow the story of the game, wherever home is today.', 'Choose a memory. Keep the connection going.'] },
  { id: 'tokyo', city: 'Tokyo', type: 'Discovery fan', caption: 'L’inizio di una nuova storia.', title: 'A NEW CITY.\nYOUR CLUB.', intro: 'Scoprire il Club attraverso calcio e cultura. Un ingresso comprensibile, anche dall’altra parte del mondo.', language: 'English', focus: 'Scoprire Napoli', editorial: 'The city behind the shirt', action: 'Discover match mode', cultural: 'Storie', recap: 'La curiosità diventa un nuovo legame.', match: ['Discover the matchday ritual. Choose a recap if following live does not fit your day.', 'An essential match story, designed to make the game easier to follow.', 'Catch up in your own time. Explore the culture behind the club.'] },
] as const;
export const culture = [
  { name: 'Luoghi', word: 'QUI.', sub: 'La città come punto di incontro.', copy: 'Un appuntamento, una strada, un tragitto condiviso. Il matchday comincia nei luoghi a cui diamo un significato.', format: 'Napoli Places', proposal: 'Una serie di itinerari editoriali legati al rapporto tra città e tifo. Luoghi e accessibilità da verificare prima della pubblicazione.' },
  { name: 'Storie', word: 'NOI.', sub: 'La maglia come memoria collettiva.', copy: 'C’è chi ricorda una partita. Chi la persona con cui l’ha vista. A volte il calcio resta proprio in quel dettaglio.', format: 'Napoli Stories', proposal: 'Microstorie in più lingue, raccolte con il consenso dei protagonisti. Nessuna testimonianza reale è utilizzata in questa demo.' },
  { name: 'Parole', word: 'CASA.', sub: 'Una parola, molti modi di sentirla.', copy: 'Può essere un posto. Una voce. Un colore visto per strada, a migliaia di chilometri. Il legame comincia quando qualcosa diventa familiare.', format: 'Napoli Language', proposal: 'Un lessico dell’appartenenza per avvicinare culture diverse. Localizzazione e revisione affidate a persone competenti.' },
  { name: 'Suoni', word: 'SENTI.', sub: 'Il rito ha una sua voce.', copy: 'L’attesa. Le conversazioni. Il rumore che sale. Prima ancora del fischio, una partita ha già un ritmo.', format: 'Napoli Sounds', proposal: 'Soundscape editoriali da produrre con registrazioni autorizzate e diritti verificati. Nessun audio riprodotto nella demo.' },
] as const;