'use client';

import { AnimatePresence, motion, MotionConfig, useReducedMotion } from 'framer-motion';
import { useCallback, useEffect, useState } from 'react';
import { flushSync } from 'react-dom';
import { scenarios, culture } from '@/content/experience-data';
import { Copy, useSite, Photo } from '@/components/site-content';

type ScenarioId = typeof scenarios[number]['id'];
const interests = ['La partita', 'La città', 'Le storie'] as const;

export function Experience() {
  const { text } = useSite();
  const [scenarioId, setScenarioId] = useState<ScenarioId>('napoli');
  const [name, setName] = useState('');
  const [interest, setInterest] = useState<typeof interests[number]>('La partita');
  const [cultureName, setCultureName] = useState<string>('Luoghi');
  const [phase, setPhase] = useState(0);
  const [copied, setCopied] = useState('');
  const [recapReady, setRecapReady] = useState(false);
  const reduced = useReducedMotion();
  const original = scenarios.find(s => s.id === scenarioId)!;
  const scenario = { ...original, ...Object.fromEntries(Object.entries(original).filter(([k,v]) => typeof v === 'string' && !['id','city','type','language','cultural'].includes(k)).map(([k,v]) => [k, text('scenario.'+original.id+'.'+k, v as string)])), match: original.match.map((v,i) => text('scenario.'+original.id+'.match.'+i,v)) };
  const originalStory = culture.find(c => c.name === cultureName)!;
  const story = {...originalStory, ...Object.fromEntries(Object.entries(originalStory).filter(([k])=>k !== 'name').map(([k,v])=>[k,text('culture.'+originalStory.name+'.'+k,v)]))};
  const displayName = name.trim() || 'IL TUO NAPOLI';
  const recapText = `NAPOLI È PERSONALE\n${displayName}\n${scenario.city} / ${scenario.type}\n${interest}\n${scenario.recap}\nUna card generata dalle scelte nella demo. Concept indipendente di Gianmarco Brandi, non affiliato a SSC Napoli.`;
  const chooseScenario = useCallback((id: ScenarioId) => { setScenarioId(id); setCultureName(scenarios.find(s => s.id === id)!.cultural); setCopied(''); setRecapReady(false); }, []);
  useEffect(() => {
    type Context = { registerTool: (tool: { name: string; title: string; description: string; inputSchema: object; annotations: object; execute: (input: unknown) => object }, options: { signal: AbortSignal }) => void | Promise<void> };
    const context = (document as Document & { modelContext?: Context }).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    try {
      void Promise.resolve(context.registerTool({ name: 'configure_fan_scenario', title: 'Scegli il punto di vista', description: 'Cambia lo scenario della demo. Aggiorna home, card, recap, cultura e Match Mode. Non crea profili e non invia dati.', inputSchema: { type: 'object', properties: { scenario: { type: 'string', enum: scenarios.map(s => s.id) } }, required: ['scenario'], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: false }, execute(input) {
        if (!input || typeof input !== 'object' || Array.isArray(input) || Object.keys(input).length !== 1 || !('scenario' in input) || !scenarios.some(s => s.id === input.scenario)) throw new Error('Scenario non valido');
        const id = input.scenario as ScenarioId;
        flushSync(() => chooseScenario(id));
        return { scenario: id, scope: 'local-demo-only', profileCreated: false };
      } }, { signal: lifecycle.signal })).catch(() => {});
    } catch { /* Optional progressive enhancement; the visible controls always remain available. */ }
    return () => lifecycle.abort();
  }, [chooseScenario]);
  async function copyRecap() { try { await navigator.clipboard.writeText(recapText); setCopied('Testo del recap copiato.'); } catch { setCopied('La copia non è disponibile in questo browser. Puoi selezionare il testo del recap qui sotto.'); } }
  function downloadRecap() { const url = URL.createObjectURL(new Blob([recapText], { type: 'text/plain;charset=utf-8' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'il-mio-napoli-demo.txt'; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setCopied('Recap testuale scaricato.'); }
  return <MotionConfig reducedMotion="user">
    <section className="section experience-section" id="esperienza" aria-labelledby="experience-title">
      <div className="section-label"><span><Copy id="experience.1">03 / SCENARI PERSONALIZZATI</Copy></span><span><Copy id="experience.2">Prototipo interattivo · Scegli un punto di vista</Copy></span></div>
      <div className="experience-heading"><h2 id="experience-title"><Copy id="experience.3">LO STESSO NAPOLI.<br />IL <span className="blue-light">TUO</span> NAPOLI.</Copy></h2><p><Copy id="experience.4">Cambia città. Cambiano priorità, contenuti e racconto.<br /><span className="muted-light">Quattro scenari ipotetici. Nessun profilo reale.</span></Copy></p></div>
      <div className="scenario-layout"><fieldset className="scenario-selector"><legend><Copy id="experience.5">Esplora come tifoso di</Copy></legend>{scenarios.map((s, index) => <label key={s.id} className={scenarioId === s.id ? 'scenario-option selected' : 'scenario-option'}><input type="radio" name="scenario" value={s.id} checked={scenarioId === s.id} onChange={() => chooseScenario(s.id)} /><span className="scenario-number">0{index + 1}</span><span><strong>{s.city}</strong><small>{s.type}</small></span><span className="scenario-arrow" aria-hidden="true">↗</span></label>)}</fieldset>
      <div className="app-prototype" aria-label="Anteprima della home personalizzata"><div className="prototype-bar"><span><Copy id="experience.6">MY NAPOLI</Copy></span><span>DEMO / {scenario.language === 'English' ? 'EN' : 'IT'}</span></div><AnimatePresence mode="wait" initial={false}><motion.div key={scenario.id} initial={{ opacity: 0, y: reduced ? 0 : 12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} transition={{ duration: reduced ? 0 : .22 }} className="prototype-content"><Photo slot={scenario.id === 'napoli' ? 'scenario-stadium' : 'scenario-city'} className="prototype-photo" /><div className="prototype-location"><span>{scenario.city} / {scenario.type}</span><span aria-hidden="true">↗</span></div><h3 lang={scenario.language === 'English' ? 'en' : 'it'}>{scenario.title.split('\n').map(line => <span key={line}>{line}</span>)}</h3><p>{scenario.caption}</p><a className="prototype-action" href="#match-mode" lang={scenario.language === 'English' ? 'en' : 'it'}>{scenario.action}<span aria-hidden="true">↗</span></a><div className="prototype-story"><span className="eyebrow"><Copy id="experience.7">CITY / CULTURE</Copy></span><a href="#cultura" lang={scenario.language === 'English' ? 'en' : 'it'}>{scenario.editorial} <span aria-hidden="true">→</span></a></div></motion.div></AnimatePresence><div className="prototype-bottom"><span><Copy id="experience.8">Scelte, non etichette.</Copy></span><a href="#my-napoli">Il tuo profilo ↗</a></div></div></div>
      <div className="scenario-explanation" aria-live="polite" aria-atomic="true"><span className="eyebrow"><Copy id="experience.9">PERCHÉ CAMBIA</Copy></span><p>{scenario.intro}</p><dl><div><dt>Lingua proposta</dt><dd>{scenario.language}</dd></div><div><dt>Priorità</dt><dd>{scenario.focus}</dd></div></dl></div><p className="demo-note"><Copy id="experience.10">Le città sono scorciatoie narrative. Nel prodotto reale sarebbero le preferenze dichiarate a guidare l’esperienza, con possibilità di cambiarle o scegliere una home generica.</Copy></p>
    </section>
    <section className="section identity-section" id="my-napoli" aria-labelledby="identity-title"><div className="section-label"><span><Copy id="experience.11">04 / MY NAPOLI</Copy></span><span><Copy id="experience.12">Un’identità, non un punteggio</Copy></span></div><div className="identity-grid"><div><h2 id="identity-title"><Copy id="experience.13">NON UN ACCOUNT.<br />UN MODO DI<br /><span className="blue-light">APPARTENERE.</span></Copy></h2><p className="identity-copy"><Copy id="experience.14">Il profilo racconta il legame che scegli.<br />Nessuna classifica di chi tifa di più.</Copy></p><div className="profile-controls"><label htmlFor="fan-name"><Copy id="experience.15">Come vuoi chiamare la tua card?</Copy></label><input id="fan-name" value={name} onChange={e => { setName(e.target.value); setRecapReady(false); setCopied(''); }} maxLength={24} placeholder="Il tuo nome o un alias" autoComplete="off" aria-describedby="name-note" /><p id="name-note" className="field-note"><Copy id="experience.16">Facoltativo. Resta solo in questa pagina, fino al ricaricamento.</Copy></p><fieldset className="interest-selector"><legend><Copy id="experience.17">Cosa ti avvicina al Napoli?</Copy></legend>{interests.map(item => <label key={item} className={interest === item ? 'interest-chip active' : 'interest-chip'}><input type="radio" name="interest" checked={interest === item} onChange={() => { setInterest(item); setRecapReady(false); setCopied(''); }} />{item}</label>)}</fieldset></div></div><div className="fan-card-stage"><motion.div className="fan-card" animate={{ rotate: reduced ? 0 : -5 }} transition={{ duration: .5 }}><Photo slot="card" className="card-photo" /><div className="fan-card-top"><span><Copy id="experience.18">MY NAPOLI</Copy></span><span><Copy id="experience.19">PERSONAL EDITION</Copy></span></div><div className="card-orbits" aria-hidden="true"><i /><i /><i /></div><div className="fan-card-name"><span><Copy id="experience.20">UN SOLO CLUB. IL TUO LEGAME.</Copy></span><strong>{displayName}</strong></div><div className="fan-card-data"><div><small><Copy id="experience.21">PUNTO DI VISTA</Copy></small><span>{scenario.city}</span></div><div><small><Copy id="experience.22">LA TUA PASSIONE</Copy></small><span>{interest}</span></div></div><div className="fan-card-footer"><span><Copy id="experience.23">ONE CLUB. YOUR STORY.</Copy></span><span><Copy id="experience.24">DEMO</Copy></span></div></motion.div><p className="card-caption"><Copy id="experience.25">Card dimostrativa · Nessuna membership attivata</Copy></p></div></div></section>
    <section className="section recap-section paper" id="recap" aria-labelledby="recap-title"><div className="section-label"><span><Copy id="experience.26">05 / NAPOLI RECAP</Copy></span><span><Copy id="experience.27">Dalle scelte a una storia</Copy></span></div><div className="recap-grid"><div className="recap-poster"><Photo slot="recap" className="poster-photo" /><div className="poster-top"><span><Copy id="experience.28">MY NAPOLI</Copy></span><span><Copy id="experience.29">YOUR STORY, SO FAR.</Copy></span></div><span className="poster-mini">{scenario.city} / {interest}</span><div className="poster-word" aria-hidden="true">IO.<br />NOI.<br /><span><Copy id="experience.30">NAPOLI.</Copy></span></div><div className="poster-bottom"><strong>{displayName}</strong><p>{scenario.recap}</p></div></div><div className="recap-copy"><h2 id="recap-title"><Copy id="experience.31">IL TIFO PASSA.<br /><span className="blue-text">LA STORIA RESTA.</span></Copy></h2><p><Copy id="experience.32">Un recap che trasforma momenti e preferenze in un racconto personale. Da ritrovare. Da condividere. Da sentire proprio.</Copy></p><p className="muted"><Copy id="experience.33">Qui il racconto nasce solo dalle scelte della demo. In un prodotto connesso potrebbe utilizzare attività autorizzate e verificate, con un’AI che aiuta a raccontarle senza inventarle.</Copy></p><button className="solid-button" onClick={() => { setRecapReady(true); setCopied(''); }}>Componi il tuo recap <span aria-hidden="true">↗</span></button><div aria-live="polite">{recapReady && <div className="recap-result"><h3><Copy id="experience.34">La tua storia, in questa demo</Copy></h3><p className="recap-text">{recapText}</p><div className="recap-actions"><button onClick={copyRecap}><Copy id="experience.35">Copia testo</Copy></button><button onClick={downloadRecap}><Copy id="experience.36">Scarica testo</Copy></button></div></div>}</div><p className="feedback" role="status">{copied}</p></div></div></section>
    <section className="section culture-section" id="cultura" aria-labelledby="culture-title"><div className="section-label"><span><Copy id="experience.37">06 / CITY & CULTURE LAYER</Copy></span><span><Copy id="experience.38">Il Club è anche un mondo da scoprire</Copy></span></div><div className="culture-heading"><h2 id="culture-title"><Copy id="experience.39">LA MAGLIA HA UN COLORE.<br />LA CITTÀ, <span className="serif-word">mille voci.</span></Copy></h2><p><Copy id="experience.40">Il calcio apre una porta.<br />La cultura dà un motivo per restare.</Copy></p></div><Photo slot="culture" className="culture-photo" /><div className="culture-browser"><fieldset className="culture-selector"><legend className="sr-only"><Copy id="experience.41">Scegli una rubrica culturale</Copy></legend>{culture.map((item, index) => <label key={item.name} className={cultureName === item.name ? 'culture-tab active' : 'culture-tab'}><input type="radio" name="culture" checked={cultureName === item.name} onChange={() => setCultureName(item.name)} /><span>0{index + 1}</span>{item.name}<span aria-hidden="true">↗</span></label>)}</fieldset><article className="culture-story" aria-live="polite"><div className="culture-word" aria-hidden="true">{story.word}</div><div><span className="eyebrow">{story.format} / Esempio editoriale</span><h3>{story.sub}</h3><p>{story.copy}</p><p className="culture-proposal">{story.proposal}</p></div></article></div></section>
    <section className={`section match-section phase-${phase}`} id="match-mode" aria-labelledby="match-title"><div className="section-label"><span><Copy id="experience.42">07–08 / MATCH MODE</Copy></span><span><Copy id="experience.43">Simulazione · Nessuna partita in diretta</Copy></span></div><div className="match-heading"><h2 id="match-title"><Copy id="experience.44">QUANDO SI GIOCA,<br /><span className="outline-text">CAMBIA TUTTO.</span></Copy></h2><p><Copy id="experience.45">La stessa relazione.<br />Tre momenti, tre priorità.</Copy></p></div><fieldset className="phase-selector"><legend><Copy id="experience.46">Esplora il momento partita</Copy></legend>{['Prima', 'Durante', 'Dopo'].map((item, index) => <label key={item} className={phase === index ? 'phase active' : 'phase'}><input type="radio" name="phase" checked={phase === index} onChange={() => setPhase(index)} /><span>0{index + 1}</span>{item}</label>)}</fieldset><div className="match-display"><Photo slot="match" className="match-photo" /><div className="match-display-top"><span>MATCH MODE / {scenario.city}</span><span><Copy id="experience.47">DEMO</Copy></span></div><div className="match-body"><div><span className="eyebrow">{['L’ATTESA', 'LA PRESENZA', 'IL RICORDO'][phase]}</span><AnimatePresence mode="wait" initial={false}><motion.h3 key={phase} initial={{ opacity: 0, x: reduced ? 0 : -15 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0 }} transition={{ duration: reduced ? 0 : .18 }}>{['CI SIAMO\nQUASI.', 'SOLO\nLA PARTITA.', 'RESTA\nCON TE.'][phase].split('\n').map(line => <span key={line}>{line}</span>)}</motion.h3></AnimatePresence></div><div className="match-detail" aria-live="polite"><p lang={scenario.language === 'English' ? 'en' : 'it'}>{scenario.match[phase]}</p><div className="match-items">{[['Prepararsi', 'Scegliere il rito', 'Informarsi'], ['Seguire il racconto', 'Vivere il momento', 'Ridurre il rumore'], ['Ritrovare la storia', 'Scegliere un ricordo', 'Comporre il recap']][phase].map(item => <span key={item}>{item}</span>)}</div><a href={phase === 2 ? '#recap' : '#my-napoli'}>{phase === 2 ? 'Vai al tuo recap' : 'Personalizza il tuo Napoli'} <span aria-hidden="true">↗</span></a></div></div><p className="match-disclaimer"><Copy id="experience.48">Contenuti di esempio. Risultati, video, ticketing e notifiche richiederebbero fonti ufficiali e integrazioni dedicate.</Copy></p></div></section>
  </MotionConfig>;
}
