'use client';
/* eslint-disable @next/next/no-img-element -- Studio previews user-uploaded data URLs, which have no Next image optimizer in this static export. */

import { useEffect, useRef, useState, type ChangeEvent } from 'react';
import Link from 'next/link';
import { defaultSite, safeImage, validateSite, type SiteData, type Project } from './site-content';
import { publicPath } from '@/lib/base-path';
import groups from '@/content/text-groups.json';
import './studio.css';

const sectionNames: Record<string,string>={nav:'Navigazione',hero:'Apertura',idea:'Big idea',now:'NOW',card:'My Napoli',together:'TOGETHER',yours:'YOURS',loop:'Product loop',strategy:'Strategia',days:'90 giorni',person:'Gianmarco',legal:'Note'};
const photoNames: Record<string,string>={hero:'Apertura', 'story-city':'Racconto / città','story-stadium':'Racconto / stadio','scenario-stadium':'Scenario Napoli','scenario-city':'Scenari dal mondo',card:'My Napoli / card',recap:'Napoli Recap',culture:'City & Culture',match:'Match Mode'};
type Tab='Testi'|'Immagini'|'Brand'|'Lavori'|'Contatti';
function database(): Promise<IDBDatabase> { return new Promise((resolve,reject)=>{const request=indexedDB.open('napoli-personale-studio',1);request.onupgradeneeded=()=>request.result.createObjectStore('drafts');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);}); }
async function readDraft() { const db=await database();try{return await new Promise<SiteData|undefined>((resolve,reject)=>{const request=db.transaction('drafts').objectStore('drafts').get('current');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}finally{db.close();} }
async function writeDraft(data:SiteData) {const db=await database();try{await new Promise<void>((resolve,reject)=>{const tx=db.transaction('drafts','readwrite');tx.objectStore('drafts').put(data,'current');tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}finally{db.close();}}
function readImage(file:File):Promise<string> {return new Promise((resolve,reject)=>{
  if (!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type) || file.size>8*1024*1024) {reject(new Error('Scegli un PNG, JPG, WebP o GIF fino a 8 MB.'));return;}
  const reader=new FileReader();reader.onerror=()=>reject(new Error('Impossibile leggere il file.'));reader.onload=()=>{const src=String(reader.result);const image=new Image();image.onload=()=>resolve(src);image.onerror=()=>reject(new Error('Il file non è un’immagine valida.'));image.src=src;};reader.readAsDataURL(file);
});}
function download(data:SiteData) {const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='napoli-personale-progetto.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export function Studio() {
  const [data,setData]=useState<SiteData>(structuredClone(defaultSite));const [tab,setTab]=useState<Tab>('Testi');const [group,setGroup]=useState('hero');const [language,setLanguage]=useState<'it'|'en'>('it');const [query,setQuery]=useState('');
  const [status,setStatus]=useState('Caricamento della bozza…');const [ready,setReady]=useState(false);const [dirty,setDirty]=useState(false);const [busy,setBusy]=useState(false);const [mobile,setMobile]=useState(false);const [showPreview,setShowPreview]=useState(false);const [selected,setSelected]=useState('');const [history,setHistory]=useState<SiteData[]>([]);
  const frame=useRef<HTMLIFrameElement>(null);const dataRef=useRef(data);const revision=useRef(0);const [previewReady,setPreviewReady]=useState(false);
  useEffect(()=>{dataRef.current=data;},[data]);
  useEffect(()=>{let active=true;readDraft().then(d=>{if(!active)return;if(d){setData(validateSite(d));setStatus('Bozza recuperata da questo browser.');}else setStatus('Pronto. Nessuna bozza salvata.');}).catch(()=>{if(active)setStatus('Archivio locale non disponibile. Puoi comunque modificare ed esportare.');}).finally(()=>{if(active)setReady(true);});return()=>{active=false;};},[]);
  useEffect(()=>{const message=(e:MessageEvent)=>{if(e.origin!==location.origin||e.source!==frame.current?.contentWindow)return;if(e.data?.type==='napoli:ready'){setPreviewReady(true);frame.current?.contentWindow?.postMessage({type:'napoli:preview',content:dataRef.current},location.origin);}if(e.data?.type==='napoli:select' && typeof e.data.id==='string'){const id=e.data.id;setTab('Testi');setQuery('');setGroup((groups as Record<string,string>)[id]||'hero');setSelected(id);setShowPreview(false);setTimeout(()=>document.getElementById('edit-'+id)?.scrollIntoView({block:'center',behavior:'smooth'}),100);}};window.addEventListener('message',message);return()=>window.removeEventListener('message',message);},[]);
  useEffect(()=>{if(!previewReady)return;const timer=setTimeout(()=>frame.current?.contentWindow?.postMessage({type:'napoli:preview',content:data},location.origin),250);return()=>clearTimeout(timer);},[data,previewReady]);
  useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave);},[dirty]);
  function update(next:SiteData) {if(new TextEncoder().encode(JSON.stringify(next)).length>40*1024*1024){setStatus('Il progetto supera 40 MB. Usa immagini più leggere prima di aggiungerne altre.');return;}setHistory(h=>[...h.slice(-9),dataRef.current]);dataRef.current=next;setData(next);revision.current++;setDirty(true);setStatus('Modifiche in anteprima · non ancora salvate.');}
  function change(mutator:(draft:SiteData)=>void) {const draft=structuredClone(dataRef.current);mutator(draft);update(draft);}
  async function save() {setBusy(true);const n=revision.current;try{const valid=validateSite(dataRef.current);await writeDraft(valid);if(n===revision.current)setDirty(false);setStatus(n===revision.current?'Bozza salvata su questo browser. La versione online non è cambiata.':'Bozza salvata. Ci sono altre modifiche da salvare.');}catch(e){setStatus(e instanceof Error?e.message:'Salvataggio non riuscito. Esporta una copia del progetto.');}finally{setBusy(false);}}
  async function importProject(event:ChangeEvent<HTMLInputElement>) {const file=event.target.files?.[0];event.target.value='';if(!file)return;setBusy(true);try{if(file.size>40*1024*1024)throw new Error('Il progetto supera 40 MB.');const next=validateSite(JSON.parse(await file.text()));update(next);setStatus('Progetto importato in anteprima. Salva la bozza per conservarlo.');}catch(e){setStatus(e instanceof Error?e.message:'Importazione non riuscita.');}finally{setBusy(false);}}
  async function upload(event:ChangeEvent<HTMLInputElement>,apply:(src:string)=>void) {const file=event.target.files?.[0];event.target.value='';if(!file)return;setBusy(true);try{apply(await readImage(file));}catch(e){setStatus(e instanceof Error?e.message:'Caricamento non riuscito.');}finally{setBusy(false);}}
  function projectChange(id:string,key:keyof Project,value:string|boolean) {change(d=>{const p=d.identity.projects.find(p=>p.id===id);if(p)Object.assign(p,{[key]:value});});}
  const fields=Object.entries(language==='it'?data.texts:data.translations).filter(([id,value])=>query?value.toLocaleLowerCase().includes(query.toLocaleLowerCase()):((groups as Record<string,string>)[id]||'hero')===group);
  return <div className="studio-shell">
    <header className="studio-top"><div><Link href="/">GB / Napoli è personale</Link><h1>Il tuo studio.</h1></div><div className="studio-actions"><button disabled={!ready||busy||!history.length} onClick={()=>{const prev=history.at(-1);if(prev){setHistory(h=>h.slice(0,-1));dataRef.current=prev;setData(prev);revision.current++;setDirty(true);setStatus('Ultima modifica annullata.');}}}>Annulla</button><button disabled={!ready||busy} className="studio-primary" onClick={save}>{busy?'Attendi…':'Salva bozza'}</button><button disabled={!ready||busy} onClick={()=>{try{download(validateSite(data));setStatus('Copia esportata. Allegala a questa conversazione per aggiornare il sito online.');}catch(e){setStatus((e as Error).message);}}}>Esporta progetto ↓</button></div></header>
    <div className="studio-notice"><strong>Bozza privata nel tuo browser.</strong> Modifica e controlla l’anteprima. Per aggiornare il sito online, esporta il progetto e allegalo alla conversazione con Codex. <label className="studio-import">Importa progetto<input type="file" accept=".json,application/json" onChange={importProject} disabled={!ready||busy}/></label></div>
    <div className="studio-status" role="status">{dirty?'● ':''}{status}</div>
    <div className="studio-mobile-toggle"><button aria-pressed={!showPreview} onClick={()=>setShowPreview(false)}>Modifica</button><button aria-pressed={showPreview} onClick={()=>setShowPreview(true)}>Anteprima</button></div>
    <div className={`studio-workspace ${showPreview?'show-preview':''}`}>
      <aside className="studio-panel" aria-label="Pannello di modifica"><nav className="studio-tabs" aria-label="Categorie dell’editor">{(['Testi','Immagini','Brand','Lavori','Contatti'] as Tab[]).map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
      <fieldset disabled={!ready||busy} className="studio-fields"><legend className="sr-only">{tab}</legend>
        {tab==='Testi'&&<><h2>Le parole, a modo tuo.</h2><p>Seleziona una sezione o clicca un testo nell’anteprima. Gli a capo restano nel sito.</p><div className="studio-language" role="group" aria-label="Lingua dei testi"><button type="button" aria-pressed={language==='it'} onClick={()=>setLanguage('it')}>Italiano</button><button type="button" aria-pressed={language==='en'} onClick={()=>setLanguage('en')}>English</button></div><label>Cerca un testo<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Sezione<select value={group} onChange={e=>{setGroup(e.target.value);setQuery('');}}>{Object.entries(sectionNames).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>{fields.map(([id,value])=><label id={'edit-'+id} key={id} className={selected===id?'studio-selected':''}><span>{(language==='it'?defaultSite.texts[id]:defaultSite.translations[id])?.slice(0,75)||id}</span><textarea rows={value.length>180?6:3} maxLength={6000} value={value} onChange={e=>change(d=>{if(language==='it')d.texts[id]=e.target.value;else d.translations[id]=e.target.value;})}/></label>)}{!fields.length&&<p>Nessun testo trovato.</p>}</>}
        {tab==='Immagini'&&<><h2>Un racconto per immagini.</h2><p>Carica originali PNG, JPG, WebP o GIF, fino a 8 MB. I file restano nella bozza e nell’esportazione. Indica autore e fonte per ogni sostituzione.</p>{Object.entries(data.photos).map(([id,p])=><details key={id} className="studio-card"><summary>{photoNames[id]||id}</summary><img className="studio-thumb" src={safeImage(p.src)} alt={p.alt}/><label>Sostituisci fotografia<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>upload(e,src=>change(d=>{d.photos[id]={...p,src,author:'',source:'',license:'',licenseUrl:''};}))}/></label><label>Descrizione dell’immagine<textarea value={p.alt} maxLength={500} onChange={e=>change(d=>{d.photos[id].alt=e.target.value;})}/></label><label>Posizione verticale · {p.position}%<input type="range" min="0" max="100" value={p.position} onChange={e=>change(d=>{d.photos[id].position=Number(e.target.value);})}/></label>{(['author','source','license','licenseUrl'] as const).map((key,i)=><label key={key}>{['Autore / crediti','Link alla fonte (HTTPS)','Licenza / autorizzazione','Link alla licenza (HTTPS)'][i]}<input value={p[key]} onChange={e=>change(d=>{d.photos[id][key]=e.target.value;})}/></label>)}<label className="studio-check"><input type="checkbox" checked={p.visible} onChange={e=>change(d=>{d.photos[id].visible=e.target.checked;})}/>Mostra questa immagine</label><button onClick={()=>change(d=>{d.photos[id]=structuredClone(defaultSite.photos[id]);})}>Ripristina questa fotografia</button></details>)}</>}
        {tab==='Brand'&&<><h2>La tua firma visiva.</h2><p>Colori, caratteri, fotografia e logo si aggiornano nell’anteprima.</p><div className="studio-presets">{[['Azzurro','#0068b8','#061b2c','#8ed6ff'],['Notte','#075293','#030b17','#9cd8ff'],['Elettrico','#075bd8','#071222','#b4dcff']].map(([name,blue,night,accent])=><button key={name} onClick={()=>change(d=>{Object.assign(d.theme,{blue,night,accent});})}>{name}</button>)}</div>{(['blue','night','paper','accent'] as const).map((key,i)=><label className="studio-color" key={key}>{['Colore principale','Fondo scuro','Fondo chiaro','Accento sui fondi scuri'][i]}<input type="color" value={data.theme[key]} onChange={e=>change(d=>{d.theme[key]=e.target.value;})}/><code>{data.theme[key]}</code></label>)}<p className="studio-hint">Con colori personalizzati controlla sempre la leggibilità di testi e pulsanti.</p><label>Tipografia dei titoli<select value={data.theme.display} onChange={e=>change(d=>{d.theme.display=e.target.value;})}><option value="condensed">Condensata / editoriale</option><option value="sans">Sans / essenziale</option></select></label><label>Intensità del fondo sulle foto · {data.theme.overlay}%<input type="range" min="45" max="90" value={data.theme.overlay} onChange={e=>change(d=>{d.theme.overlay=Number(e.target.value);})}/></label><img className="studio-logo" src={safeImage(data.identity.logo)} alt="Logo personale corrente"/><label>Carica un’altra versione del tuo logo<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>upload(e,src=>change(d=>{d.identity.logo=src;}))}/></label><label>Larghezza logo · {data.theme.logoWidth}px<input type="range" min="80" max="220" value={data.theme.logoWidth} onChange={e=>change(d=>{d.theme.logoWidth=Number(e.target.value);})}/></label><p>Il logo viene mostrato nelle sue proporzioni, senza ritocchi o ricolorazioni.</p></>}
        {tab==='Lavori'&&<><h2>Qui carichi i tuoi lavori.</h2><p>Una scheda per progetto: immagini originali, contesto, contributo e crediti. Attiva la visibilità solo dopo averli verificati.</p><label className="studio-check"><input type="checkbox" checked={data.portfolioEnabled} onChange={e=>change(d=>{d.portfolioEnabled=e.target.checked;})}/>Abilita la sezione pubblica dei lavori verificati</label><button className="studio-primary" disabled={data.identity.projects.length>=30} onClick={()=>change(d=>{d.identity.projects.push({id:crypto.randomUUID(),title:'',role:'',year:'',description:'',image:'',alt:'',source:'',credits:'',verified:false});})}>+ Aggiungi un lavoro</button>{data.identity.projects.length===0&&<p className="studio-empty">Il tuo archivio è pronto a ricevere i primi progetti.</p>}{data.identity.projects.map((p,index)=><details key={p.id} className="studio-card" open><summary>{p.title||'Nuovo lavoro'}</summary>{p.image&&<img className="studio-thumb" src={safeImage(p.image)} alt={p.alt}/>}<label>Immagine originale<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>upload(e,src=>projectChange(p.id,'image',src))}/></label>{(['title','role','year','description','alt','credits','source'] as const).map((key,i)=><label key={key}>{['Titolo','Il tuo ruolo','Anno','Descrizione e contesto','Descrizione dell’immagine','Crediti / collaboratori','Link al progetto (HTTPS)'][i]}<textarea rows={key==='description'?4:2} value={p[key]} onChange={e=>projectChange(p.id,key,e.target.value)}/></label>)}<label className="studio-check"><input type="checkbox" checked={p.verified} onChange={e=>projectChange(p.id,'verified',e.target.checked)}/>Confermo ruolo e crediti</label><div className="studio-row"><button disabled={index===0} onClick={()=>change(d=>{[d.identity.projects[index-1],d.identity.projects[index]]=[d.identity.projects[index],d.identity.projects[index-1]];})}>Sposta su ↑</button><button onClick={()=>change(d=>{d.identity.projects=d.identity.projects.filter(q=>q.id!==p.id);})}>Rimuovi</button></div></details>)}</>}
        {tab==='Contatti'&&<><h2>La prossima conversazione.</h2><p>Inserisci solo i recapiti che vuoi rendere visibili. I campi vuoti non compaiono nel sito.</p>{(['name','email','cv','portfolioUrl'] as const).map((key,i)=><label key={key}>{['Nome visualizzato','Email pubblica','Link HTTPS al CV','Link HTTPS al portfolio'][i]}<input value={data.identity[key]} type={key==='email'?'email':'text'} onChange={e=>change(d=>{d.identity[key]=e.target.value;})}/></label>)}</>}
      </fieldset></aside>
      <section className="studio-preview" aria-label="Anteprima del sito"><div className="studio-preview-bar"><span>ANTEPRIMA · {dirty?'modificata':'bozza'}</span><div><button aria-pressed={!mobile} onClick={()=>setMobile(false)}>Desktop</button><button aria-pressed={mobile} onClick={()=>setMobile(true)}>Mobile</button></div></div><div className="studio-frame-wrap"><iframe ref={frame} className={mobile?'studio-frame mobile':'studio-frame'} src={`${publicPath('/')}?studio=1`} title="Anteprima interattiva di Napoli è personale"/></div></section>
    </div>
  </div>;
}
