import {chromium} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';
const base=process.env.QA_URL||'http://127.0.0.1:4173';
const report={checks:[],accessibility:[],errors:[]};
const browser=await chromium.launch({channel:'chrome',headless:true});
const output=path.resolve('../qa');
try {
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});const page=await context.newPage();
 page.on('pageerror',e=>report.errors.push(e.message));
 await page.goto(base+'/studio/',{waitUntil:'networkidle'});
 await page.getByRole('button',{name:'Salva bozza',exact:true}).waitFor();
 await page.waitForFunction(()=>!document.querySelector('.studio-primary').disabled);
 const preview=page.frameLocator('iframe');
 await preview.locator('h1').waitFor();
 await page.screenshot({path:path.join(output,'studio-desktop.png')});
 const title=page.locator('textarea').filter({hasText:'NAPOLI È'});
 await title.fill('NAPOLI È\nIL TUO MONDO.');
 await preview.getByRole('heading',{level:1,name:/IL TUO MONDO/}).waitFor();
 await page.getByRole('button',{name:'Salva bozza',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Bozza salvata su questo browser'}).waitFor();
 await page.reload({waitUntil:'networkidle'});
 await preview.getByRole('heading',{level:1,name:/IL TUO MONDO/}).waitFor();
 report.checks.push('Text edits preview, save in IndexedDB and survive reload');
 const normal=await context.newPage();await normal.goto(base);assert.match(await normal.locator('h1').innerText(),/PERSONALE/);await normal.close();
 report.checks.push('Draft does not silently modify the published homepage');
 await page.getByRole('button',{name:'Brand',exact:true}).click();
 await page.getByRole('button',{name:'Notte',exact:true}).click();
 await page.waitForTimeout(500);
 assert.equal(await preview.locator('html').evaluate(el=>el.style.getPropertyValue('--blue')),'#075293');
 await page.getByLabel('Carica un’altra versione del tuo logo').setInputFiles(path.resolve('public/assets/gianmarco-brandi-original.png'));
 await page.waitForTimeout(500);
 assert.match(await preview.locator('.logo-signature img').getAttribute('src'),/^data:image\/png;base64,/);
 report.checks.push('Brand preset and original logo upload update preview');
 await page.getByRole('button',{name:'Lavori',exact:true}).click();
 await page.getByRole('button',{name:'+ Aggiungi un lavoro'}).click();
 await page.getByLabel('Titolo',{exact:true}).fill('Progetto QA <script>');
 await page.getByLabel('Il tuo ruolo',{exact:true}).fill('Verifica del caricamento');
 await page.getByLabel('Immagine originale',{exact:true}).setInputFiles(path.resolve('public/assets/gianmarco-brandi-original.png'));
 await page.getByLabel('Descrizione dell’immagine',{exact:true}).fill('Logo originale usato soltanto nel test');
 await page.getByLabel('Crediti / collaboratori',{exact:true}).fill('Dati sintetici di test, non pubblicati');
 await page.getByLabel('Confermo ruolo e crediti: mostra il lavoro').check();
 await preview.locator('.personal-projects h3').filter({hasText:'Progetto QA <script>'}).waitFor();
 assert.equal(await preview.locator('.personal-projects script').count(),0);
 report.checks.push('Project image, role and credits display; text is escaped, unverified work stays hidden');
 const exportEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Esporta progetto'}).click();const download=await exportEvent;const exported=JSON.parse(await fs.readFile(await download.path(),'utf8'));
 assert.equal(exported.identity.projects.length,1);const raw=await fs.readFile('public/assets/gianmarco-brandi-original.png');assert.equal(exported.identity.logo,'data:image/png;base64,'+raw.toString('base64'));
 const invalid=structuredClone(exported);invalid.identity.portfolioUrl='javascript:alert(1)';
 await page.locator('.studio-import input').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});
 await page.getByRole('status').filter({hasText:'HTTPS valido'}).waitFor();
 await page.locator('.studio-import input').setInputFiles({name:'project.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});
 await page.getByRole('status').filter({hasText:'Progetto importato'}).waitFor();
 report.checks.push('Export retains original image bytes; valid reimport succeeds; unsafe URLs rejected');
 await page.getByRole('button',{name:'Contatti',exact:true}).click();await page.getByLabel('Email pubblica').fill('qa@example.test');await preview.getByRole('link',{name:'Parliamone'}).waitFor();
 for(const tab of ['Testi','Immagini','Brand','Lavori','Contatti']) {
  await page.getByRole('button',{name:tab,exact:true}).click();
  const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();report.accessibility.push({state:'studio-'+tab,violations:axe.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}))});
 }
 await page.getByRole('button',{name:'Testi',exact:true}).click();await page.getByRole('button',{name:'Salva bozza',exact:true}).click();
 await page.getByRole('status').filter({hasText:'Bozza salvata'}).waitFor();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'studio-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.getByRole('button',{name:'Anteprima',exact:true}).click();await preview.locator('h1').waitFor();await page.screenshot({path:path.join(output,'studio-mobile-preview.png')});
 report.checks.push('Studio works at 390px with editor/preview switch');
 assert.deepEqual(report.errors,[]);assert.ok(report.accessibility.every(s=>!s.violations.length));
} finally {await fs.writeFile(path.join(output,'studio-report.json'),JSON.stringify(report,null,2));await browser.close();}
console.log(JSON.stringify(report,null,2));
