import { chromium } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';

const baseURL=process.env.QA_URL||'http://127.0.0.1:4173';
const output=path.resolve('../qa');
await mkdir(output,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const report={checks:[],viewports:[],accessibility:[],errors:[]};
try {
  const context=await browser.newContext({viewport:{width:1440,height:900},acceptDownloads:true,permissions:['clipboard-read','clipboard-write']});
  const page=await context.newPage();
  page.on('pageerror',e=>report.errors.push('page: '+e.message));
  page.on('console',m=>{if(m.type()==='error')report.errors.push('console: '+m.text());});
  const response=await page.goto(baseURL,{waitUntil:'networkidle'});
  assert.equal(response.status(),200);
  await page.evaluate(()=>document.fonts.ready);
  assert.equal(await page.locator('h1').count(),1);
  assert.equal(await page.locator('a[href="/studio"]').count(),0);
  assert.equal(await page.locator('.portfolio-case').count(),9);
  assert.equal(await page.locator('.portfolio-case video').count(),1);
  assert.ok((await page.locator('h1').innerText()).includes('NAPOLI'));
  report.checks.push('Hero, independent disclaimer, nine portfolio cases and no public editor link');
  await page.locator('.np-location button').nth(3).click();
  assert.ok((await page.locator('.np-card-facts').innerText()).includes('MONDO'));
  await page.getByLabel('COME VUOI CHIAMARE LA TUA CARD?').fill('Gianmarco <test>');
  assert.ok((await page.locator('.np-card-identity').textContent()).includes('Gianmarco <test>'));
  for(const [index,slot] of ['now-prima','now-durante','now-dopo'].entries()){
    await page.locator('.np-segment button').nth(index).click();
    await page.waitForFunction(expected=>{const photos=document.querySelectorAll('.np-now-image figure[data-photo]');return photos.length===1&&photos[0].getAttribute('data-photo')===expected;},slot);
    assert.ok(await page.locator('.np-now-image img').evaluate(img=>img.complete&&img.naturalWidth>0));
  }
  await page.locator('.np-now-copy h3').filter({hasText:'SERATA'}).waitFor();
  await page.locator('#np-caption').fill('La nostra serata');
  await page.getByRole('button',{name:/SALVA NEL TUO MY NAPOLI/}).click();
  assert.ok((await page.locator('.np-saved-moments').innerText()).includes('La nostra serata'));
  assert.ok((await page.locator('.np-card-facts').innerText()).includes('1'));
  const download=page.waitForEvent('download');
  await page.getByRole('button',{name:/SCARICA IL FRAME/}).click();
  assert.match((await download).suggestedFilename(),/il-tuo-napoli/);
  await page.locator('.np-progress button').nth(3).click();
  await page.locator('.np-wrapped-stage').filter({hasText:'La nostra serata'}).waitFor();
  report.checks.push('Location, match phase, safe card input, moment, frame and wrapped flow');
  await page.locator('.np-funnel-chooser button').first().click();
  const old=await page.locator('.np-funnel-result strong').first().innerText();
  await page.locator('#np-exposure').fill('200000');
  const changed=await page.locator('.np-funnel-result strong').first().innerText();
  assert.notEqual(old,changed);
  report.checks.push('Editable strategic funnel recalculates');
  await page.getByRole('button',{name:'EN',exact:true}).click();
  assert.equal(await page.locator('html').getAttribute('lang'),'en');
  assert.ok((await page.locator('#np-idea-title').innerText()).includes('CLUB'));
  await page.getByRole('button',{name:'IT',exact:true}).click();
  assert.equal(await page.locator('html').getAttribute('lang'),'it');
  report.checks.push('Italian and English switch');
  const dead=await page.locator('a[href^="#"]').evaluateAll(links=>links.map(a=>a.getAttribute('href')).filter(h=>!document.getElementById(h.slice(1))));
  assert.deepEqual(dead,[]);
  const assets=await page.evaluate(async()=>{
    const urls=[...new Set([...document.querySelectorAll('img')].map(i=>i.src).concat([...document.querySelectorAll('video')].flatMap(v=>[v.poster,...[...v.querySelectorAll('source')].map(s=>s.src)])))].filter(Boolean);
    return Promise.all(urls.map(async url=>{const response=await fetch(url);return {url,status:response.status,type:response.headers.get('content-type')};}));
  });
  assert.deepEqual(assets.filter(a=>a.status!==200),[]);
  assert.ok(assets.some(a=>a.type?.includes('video/mp4')));
  report.checks.push('Anchors, images, posters and video resolve under the Pages path');
  for(const width of [390,768,1440,1920]){
    await page.setViewportSize({width,height:900});
    await page.goto(baseURL,{waitUntil:'networkidle'});
    await page.evaluate(()=>document.fonts.ready);
    const overflow=await page.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth}));
    report.viewports.push({width,...overflow});
    await page.screenshot({path:path.join(output,`master-${width}.png`),fullPage:true});
    const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa','best-practice']).analyze();
    report.accessibility.push({width,violations:axe.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}))});
  }
  await page.setViewportSize({width:390,height:844});
  await page.goto(baseURL,{waitUntil:'networkidle'});
  await page.locator('.np-menu').click();
  assert.equal(await page.locator('.np-menu').getAttribute('aria-expanded'),'true');
  await page.locator('.np-navigation a').first().click();
  assert.equal(await page.locator('.np-menu').getAttribute('aria-expanded'),'false');
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.reload({waitUntil:'networkidle'});
  await page.locator('.np-location button').last().focus();
  await page.keyboard.press('Enter');
  assert.equal(await page.locator('.np-location button').last().getAttribute('aria-pressed'),'true');
  report.checks.push('Mobile navigation, keyboard control, reduced motion');
  const studio=await context.newPage();
  studio.on('pageerror',e=>report.errors.push('studio: '+e.message));
  await studio.goto(baseURL+'/studio',{waitUntil:'networkidle'});
  assert.ok((await studio.locator('.studio-fields').innerText()).includes('Le parole'));
  assert.ok((await studio.locator('.studio-fields textarea').count())>0);
  await studio.getByRole('button',{name:'English'}).click();
  assert.ok((await studio.locator('.studio-fields textarea').count())>0);
  await studio.getByRole('button',{name:'Lavori'}).click();
  assert.ok((await studio.locator('.studio-fields').innerText()).includes('Mostra i lavori'));
  assert.equal(await studio.locator('.studio-card').count(),9);
  report.checks.push('Studio IT/EN text fields and editable portfolio');
  await studio.close();
  const noJS=await browser.newContext({javaScriptEnabled:false});
  const staticPage=await noJS.newPage();
  await staticPage.goto(baseURL);
  assert.ok((await staticPage.locator('h1').innerText()).includes('NAPOLI'));
  report.checks.push('Static narrative visible without JavaScript');
  await noJS.close();
} finally {
  await browser.close();
  await writeFile(path.join(output,'master-results.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify(report,null,2));
}
if(report.errors.length||report.accessibility.some(x=>x.violations.length)||report.viewports.some(x=>x.document>x.width+1))process.exitCode=1;
